# Google Agent Development Kit (ADK) Configuration
adk:
  version: "1.0.0"
  project_id: "${GOOGLE_CLOUD_PROJECT}"
  region: "${GOOGLE_CLOUD_REGION:-us-central1}"
  
agent_discovery:
  discovery_endpoint: "https://agentbuilder.googleapis.com/v1/projects/${GOOGLE_CLOUD_PROJECT}/agents"
  refresh_interval: 3600  # 1 hour
  
  available_agents:
    - name: "code-quality-analyzer"
      type: "analysis"
      capabilities: ["complexity", "maintainability", "documentation"]
    
    - name: "security-scanner"
      type: "security"
      capabilities: ["vulnerability", "secrets", "dependencies"]
    
    - name: "performance-profiler"
      type: "performance"
      capabilities: ["profiling", "bottlenecks", "optimization"]

integration:
  authentication:
    service_account_path: "${GOOGLE_APPLICATION_CREDENTIALS}"
    scopes:
      - "https://www.googleapis.com/auth/cloud-platform"
      - "https://www.googleapis.com/auth/agentbuilder"
  
  api_configuration:
    timeout: 60  # seconds
    retry_attempts: 3
    backoff_multiplier: 2

agent_orchestration:
  parallel_execution: true
  max_concurrent_agents: 5
  execution_timeout: 600  # 10 minutes
  
  failure_handling:
    retry_failed_agents: true
    continue_on_agent_failure: true
    fallback_to_local_agents: true

data_exchange:
  input_format: "structured_json"
  output_format: "structured_json"
  
  serialization:
    use_compression: true
    max_payload_size: 10485760  # 10MB

monitoring:
  metrics_collection: true
  performance_tracking: true
  cost_tracking: true
  
  alerts:
    on_failure: true
    on_timeout: true
    on_cost_threshold: true
