# GADK Runtime Configuration
# Configuration for Google Agent Development Kit integration

# Google Cloud Project Settings
project_id: ${GOOGLE_CLOUD_PROJECT_ID}
location: ${GOOGLE_CLOUD_LOCATION:us-central1}
agent_builder_location: ${AGENT_BUILDER_LOCATION:global}
dialogflow_location: ${DIALOGFLOW_LOCATION:global}

# Authentication Configuration
credentials_path: ${GOOGLE_APPLICATION_CREDENTIALS}

# Service Enablement
services:
  vertex_ai:
    enabled: ${ENABLE_VERTEX_AI:true}
    # Vertex AI specific configuration
    model_name: "gemini-1.5-pro"
    max_tokens: 4096
    temperature: 0.7
    
  discovery_engine:
    enabled: ${ENABLE_DISCOVERY_ENGINE:true}
    # Discovery Engine specific configuration
    search_tier: "SEARCH_TIER_ENTERPRISE"
    result_count: 10
    
  dialogflow:
    enabled: ${ENABLE_DIALOGFLOW:true}
    # Dialogflow specific configuration
    language_code: "en-US"
    time_zone: "America/New_York"

# Session Management
session:
  timeout: ${GADK_SESSION_TIMEOUT:3600}  # 1 hour in seconds
  max_concurrent_sessions: 10
  cleanup_interval: 300  # 5 minutes in seconds
  
# Retry and Error Handling
retry:
  max_retries: ${GADK_MAX_RETRIES:3}
  retry_delay: ${GADK_RETRY_DELAY:1.0}
  exponential_backoff: true
  max_retry_delay: 60.0

# Logging Configuration
logging:
  level: ${GADK_LOG_LEVEL:INFO}
  enable_request_logging: ${ENABLE_REQUEST_LOGGING:false}
  enable_response_logging: ${ENABLE_RESPONSE_LOGGING:false}
  log_credentials: false  # Never log credentials

# Performance Settings
performance:
  connection_pool_size: 10
  request_timeout: 30.0
  enable_caching: true
  cache_ttl: 300  # 5 minutes

# Feature Flags
features:
  enable_experimental_features: ${ENABLE_EXPERIMENTAL_FEATURES:false}
  enable_telemetry: ${ENABLE_TELEMETRY:true}
  enable_metrics_collection: ${ENABLE_METRICS:true}

# Tool Registry Configuration
tools:
  # Default tools to register with each session
  default_tools:
    - "complexity_analysis"
    - "pattern_detection"
    - "quality_control"
  
  # Tool-specific configuration
  complexity_analysis:
    max_file_size: 1048576  # 1MB
    language_support:
      - python
      - java
      - typescript
      - javascript
      - go
      
  pattern_detection:
    ml_model: "pattern-recognition-v1"
    confidence_threshold: 0.85
    
  quality_control:
    bias_prevention: true
    hallucination_detection: true