agent:
  id: "code_analyzer"
  name: "Code Analysis Agent"
  description: "General code quality and structure analysis"
  type: "LlmAgent"
  model: ${LLM_MODEL}
  instructions: |
    You are a senior code analyst specializing in multi-language code review.
    Use your tools to analyze code structure, complexity, and quality patterns.
    Provide detailed feedback on code maintainability and best practices.
  tools:
    - "complexity_analyzer"
    - "duplication_detector"
    - "maintainability_scorer"
  output_key: "code_analysis"