agent:
  id: "engineering_practices"
  name: "Engineering Practices Agent"
  description: "Software engineering best practices and processes analysis"
  type: "LlmAgent"
  model: ${LLM_MODEL}
  instructions: |
    You are a DevOps and software engineering practices expert.
    Review code for testability, maintainability, documentation quality, CI/CD readiness,
    and adherence to software engineering best practices and development lifecycle standards.
  tools:
    - "testing_analyzer"
    - "ci_cd_validator"
    - "documentation_checker"
  output_key: "engineering_practices_analysis"