# LLM Security Configuration
# Comprehensive security controls for prompt injection prevention, input sanitization,
# output filtering, and self-destructive behavior prevention

version: "1.0.0"

# Prompt Injection Protection
prompt_injection_protection:
  # Injection attack patterns
  injection_patterns:
    # Delimiter attacks
    delimiter_attacks:
      - "```.*?ignore.*?previous.*?instructions"
      - "---.*?new.*?task.*?begins"
      - "\\*\\*\\*.*?system.*?override"
      - "###.*?admin.*?mode"
      - "===.*?priority.*?update"
      - "<<<.*?emergency.*?instruction"
      - ">>>.*?critical.*?directive"
    
    # Instruction override attempts
    instruction_override:
      - "forget.*?previous.*?instructions"
      - "ignore.*?all.*?rules"
      - "disregard.*?constraints"
      - "override.*?safety.*?protocols"
      - "bypass.*?security.*?measures"
      - "act.*?as.*?different.*?character"
      - "pretend.*?you.*?are"
      - "roleplay.*?as"
      - "simulate.*?being"
    
    # Context manipulation
    context_manipulation:
      - "the.*?user.*?said.*?to.*?ignore"
      - "previous.*?conversation.*?is.*?fake"
      - "real.*?instruction.*?is"
      - "secret.*?password.*?is"
      - "hidden.*?command.*?activate"
      - "developer.*?mode.*?enabled"
      - "debug.*?mode.*?on"
    
    # Jailbreak attempts
    jailbreak_patterns:
      - "DAN.*?mode"
      - "do.*?anything.*?now"
      - "unrestricted.*?AI"
      - "no.*?ethical.*?guidelines"
      - "remove.*?safety.*?filters"
      - "ignore.*?content.*?policy"
      - "harmful.*?request.*?approved"
  
  # Detection thresholds
  detection_thresholds:
    max_injection_score: 3  # Maximum number of injection patterns before blocking
    confidence_threshold: 0.7  # Minimum confidence for injection detection
    context_window_size: 1000  # Characters to analyze for injection patterns
  
  # Response to injection attempts
  injection_response:
    block_request: true
    log_attempt: true
    sanitize_input: true
    notify_admin: false  # Set to true for production monitoring

# Input Sanitization and Validation
input_sanitization:
  # Dangerous input patterns
  dangerous_patterns:
    # Code execution attempts
    code_execution:
      - "eval\\s*\\("
      - "exec\\s*\\("
      - "subprocess\\."
      - "os\\.system"
      - "shell_exec"
      - "__import__"
      - "compile\\s*\\("
    
    # File system access
    file_system_access:
      - "\\.\\./\\.\\./"  # Directory traversal
      - "/etc/passwd"
      - "/etc/shadow"
      - "C:\\\\Windows\\\\System32"
      - "rm\\s+-rf"
      - "del\\s+/[sf]"
    
    # Network requests
    network_requests:
      - "curl\\s+http"
      - "wget\\s+http"
      - "requests\\.get"
      - "urllib\\.request"
      - "fetch\\s*\\("
    
    # Database access
    database_access:
      - "DROP\\s+TABLE"
      - "DELETE\\s+FROM"
      - "UPDATE\\s+.*\\s+SET"
      - "UNION\\s+SELECT"
      - "INSERT\\s+INTO"
      - "'\\s*OR\\s*'1'='1"
    
    # Credential patterns
    credentials:
      - "password\\s*[=:]"
      - "api[_-]?key\\s*[=:]"
      - "secret[_-]?key\\s*[=:]"
      - "token\\s*[=:]"
      - "authorization:\\s*Bearer"
  
  # Sanitization rules
  sanitization_rules:
    remove_suspicious_delimiters: true
    escape_special_characters: true
    limit_input_length: 10000  # Maximum input length
    normalize_whitespace: true
    remove_null_bytes: true
  
  # Validation rules
  validation_rules:
    max_injection_patterns: 2
    max_suspicious_keywords: 5
    require_context_relevance: true
    block_encoded_payloads: true

# Self-Destructive Behavior Prevention
self_destructive_prevention:
  # Configuration modification attempts
  config_modification_patterns:
    - "modify.*?config"
    - "update.*?settings"
    - "change.*?parameters"
    - "override.*?rules"
    - "disable.*?security"
    - "turn.*?off.*?validation"
    - "bypass.*?checks"
    - "remove.*?constraints"
  
  # System manipulation attempts
  system_manipulation:
    - "shutdown.*?system"
    - "restart.*?service"
    - "kill.*?process"
    - "delete.*?files"
    - "modify.*?logs"
    - "clear.*?history"
    - "format.*?drive"
  
  # Agent behavior modification
  agent_modification:
    - "ignore.*?instructions"
    - "act.*?differently"
    - "change.*?personality"
    - "modify.*?behavior"
    - "override.*?purpose"
    - "forget.*?mission"
    - "become.*?malicious"
  
  # Prevention measures
  prevention_measures:
    block_config_access: true
    prevent_system_calls: true
    monitor_behavior_changes: true
    log_modification_attempts: true
    escalate_serious_attempts: true

# Output Sanitization and Data Leakage Prevention
output_sanitization:
  # Sensitive data patterns
  sensitive_patterns:
    # Credentials and secrets
    credentials:
      - "password[\\s=:]+[\\w\\d!@#$%^&*]+"
      - "api[_-]?key[\\s=:]+[\\w\\d-]+"
      - "secret[_-]?key[\\s=:]+[\\w\\d-]+"
      - "token[\\s=:]+[\\w\\d.-]+"
      - "bearer\\s+[\\w\\d.-]+"
      - "basic\\s+[A-Za-z0-9+/=]+"
    
    # Personal information
    personal_info:
      - "\\b\\d{3}-\\d{2}-\\d{4}\\b"  # SSN
      - "\\b\\d{16}\\b"  # Credit card
      - "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}\\b"  # Email
      - "\\b\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\b"  # IP address
    
    # File paths and system info
    system_info:
      - "/home/[\\w]+/"
      - "/Users/[\\w]+/"
      - "C:\\\\Users\\\\[\\w]+\\\\"
      - "/etc/[\\w/]+"
      - "/var/[\\w/]+"
    
    # Database connection strings
    database_strings:
      - "jdbc:[\\w:/@.-]+"
      - "mongodb://[\\w:/@.-]+"
      - "postgres://[\\w:/@.-]+"
      - "mysql://[\\w:/@.-]+"
  
  # Data leakage prevention
  leakage_prevention:
    redact_credentials: true
    mask_personal_info: true
    remove_file_paths: true
    sanitize_error_messages: true
    limit_technical_details: true
  
  # Redaction settings
  redaction_settings:
    credential_replacement: "[REDACTED_CREDENTIAL]"
    personal_info_replacement: "[REDACTED_PII]"
    file_path_replacement: "[REDACTED_PATH]"
    ip_address_replacement: "[REDACTED_IP]"

# Security Monitoring and Logging
security_monitoring:
  # Event categories to monitor
  monitored_events:
    - prompt_injection_attempts
    - input_sanitization_triggers
    - output_redaction_events
    - self_destructive_behavior_attempts
    - configuration_access_attempts
    - suspicious_pattern_detections
  
  # Logging configuration
  logging_config:
    log_level: "WARNING"  # INFO, WARNING, ERROR, CRITICAL
    log_format: "security"  # Include security context
    include_request_context: true
    include_user_context: false  # Set to true if user tracking needed
    max_log_entry_length: 1000
  
  # Alert thresholds
  alert_thresholds:
    max_injection_attempts_per_hour: 5
    max_sanitization_triggers_per_session: 10
    max_blocked_requests_per_user: 3
    critical_pattern_immediate_alert: true
  
  # Response actions
  response_actions:
    block_after_threshold: true
    rate_limit_aggressive_users: true
    escalate_to_admin: false  # Set to true for production
    temporary_user_suspension: false

# Error Handling for Security Events
security_error_handling:
  # Default responses
  default_responses:
    injection_detected: "I cannot process requests that appear to contain instruction manipulation. Please rephrase your request."
    suspicious_input: "Your request contains patterns that cannot be processed. Please modify your input."
    blocked_output: "The response contained sensitive information and has been blocked for security."
    system_access_denied: "Access to system-level operations is not permitted."
  
  # Fallback behavior
  fallback_behavior:
    fail_secure: true  # Fail closed rather than open
    provide_generic_response: true
    log_security_event: true
    maintain_user_session: false  # Terminate session on serious violations

# Security Feature Toggles
security_features:
  # Enable/disable security modules
  prompt_injection_protection: true
  input_sanitization: true
  output_sanitization: true
  self_destructive_prevention: true
  security_monitoring: true
  
  # Security levels
  security_level: "strict"  # Options: permissive, standard, strict, paranoid
  
  # Development vs Production
  development_mode: false  # Relaxed security for development
  production_hardening: true  # Enhanced security for production