# ADK SessionService Configuration
session:
  timeout: 3600  # 1 hour
  max_active_sessions: 100
  cleanup_interval: 300  # 5 minutes
  
  # Session state management
  state_prefixes:
    app: "app:*"
    user: "user:*"
    temp: "temp:*"
  
  # Session persistence
  persistence:
    enabled: true
    storage_type: "memory"  # Will be Neo4j in Milestone 2.2
    
  # Session cleanup
  cleanup:
    expired_sessions: true
    orphaned_state: true