# Bias Prevention and Quality Control Configuration
# This configuration defines strategies to prevent bias and hallucination in AI agent analysis

version: "1.0.0"

# Cognitive bias prevention
cognitive_bias_prevention:
  enable: true

# Technical bias prevention  
technical_bias_prevention:
  enable: true

bias_prevention:
  # Cognitive bias mitigation
  cognitive_bias:
    # Confirmation bias - tendency to favor information that confirms existing beliefs
    confirmation_bias:
      enable_contradictory_analysis: true
      require_alternative_perspectives: true
      validate_against_opposing_evidence: true
      minimum_counterarguments: 2
      
    # Anchoring bias - over-reliance on first piece of information
    anchoring_bias:
      randomize_analysis_order: true
      use_multiple_starting_points: true
      avoid_initial_assumption_persistence: true
      
    # Availability heuristic - overestimating likelihood of remembered events
    availability_heuristic:
      use_statistical_baselines: true
      reference_industry_standards: true
      avoid_recent_event_overweighting: true
      
    # Recency bias - giving more weight to recent information
    recency_bias:
      balance_historical_patterns: true
      weight_by_relevance_not_recency: true
      include_long_term_trends: true

  # Technical bias mitigation
  technical_bias:
    # Language preference bias
    language_bias:
      apply_consistent_standards: true
      use_language_agnostic_metrics: true
      avoid_subjective_language_rankings: true
      
    # Framework/technology bias
    technology_bias:
      evaluate_based_on_requirements: true
      avoid_personal_technology_preferences: true
      use_objective_criteria: true
      
    # Pattern recognition bias
    pattern_bias:
      validate_pattern_significance: true
      require_statistical_evidence: true
      avoid_pattern_overinterpretation: true

  # Cultural and contextual bias
  contextual_bias:
    # Industry context
    industry_context:
      adapt_standards_to_industry: true
      consider_regulatory_requirements: true
      account_for_business_constraints: true
      
    # Team size and maturity
    team_context:
      adjust_recommendations_to_team_size: true
      consider_team_experience_level: true
      account_for_resource_constraints: true
      
    # Legacy vs greenfield
    codebase_context:
      differentiate_legacy_vs_new: true
      adjust_refactoring_recommendations: true
      consider_migration_constraints: true

quality_gates:
  # Pre-analysis gates
  pre_analysis:
    input_validation:
      validate_code_syntax: true
      check_file_completeness: true
      verify_context_adequacy: true
      
    resource_validation:
      check_memory_availability: true
      verify_timeout_settings: true
      validate_llm_connectivity: true

  # During analysis gates
  analysis_gates:
    progress_validation:
      monitor_analysis_coherence: true
      check_intermediate_results: true
      validate_reasoning_steps: true
      
    quality_checkpoints:
      verify_finding_quality: true
      check_confidence_calibration: true
      validate_evidence_strength: true

  # Post-analysis gates
  post_analysis:
    result_validation:
      validate_output_format: true
      check_finding_completeness: true
      verify_recommendation_feasibility: true
      
    quality_assurance:
      run_consistency_checks: true
      validate_against_thresholds: true
      perform_sanity_checks: true

# Monitoring and feedback
monitoring:
  # Bias detection
  bias_detection:
    # Pattern monitoring
    pattern_monitoring:
      track_language_preferences: true
      monitor_severity_distributions: true
      detect_finding_patterns: true
      
    # Feedback analysis
    feedback_analysis:
      analyze_user_corrections: true
      track_false_positive_rates: true
      monitor_confidence_accuracy: true
      
    # Drift detection
    drift_detection:
      monitor_analysis_consistency: true
      detect_model_degradation: true
      track_performance_changes: true

  # Quality metrics
  quality_metrics:
    # Accuracy metrics
    accuracy_metrics:
      precision: true
      recall: true
      f1_score: true
      confidence_calibration: true
      
    # Consistency metrics
    consistency_metrics:
      inter_analysis_consistency: true
      cross_agent_agreement: true
      temporal_stability: true
      
    # Bias metrics
    bias_metrics:
      fairness_across_languages: true
      consistency_across_projects: true
      stability_across_time: true

# Continuous improvement
improvement:
  # Learning from feedback
  feedback_learning:
    user_feedback_integration: true
    expert_review_integration: true
    peer_agent_feedback: true
    
  # Model updating
  model_updating:
    regular_calibration: true
    bias_correction_updates: true
    performance_optimization: true
    
  # Configuration adaptation
  config_adaptation:
    threshold_optimization: true
    parameter_tuning: true
    strategy_refinement: true
