# Quality Control Rules and Validation Configuration
# Defines rules for ensuring high-quality analysis results

version: "1.0.0"

# Quality gates for ensuring analysis quality
quality_gates:
  minimum_confidence: 0.6
  maximum_findings_per_file: 25
  require_evidence: true

# Severity levels configuration for quality control
severity_levels:
  CRITICAL:
    threshold: 0.9
    max_per_file: 3
    require_immediate_action: true
  HIGH:
    threshold: 0.8
    max_per_file: 5
    require_priority_action: true
  MEDIUM:
    threshold: 0.7
    max_per_file: 10
    require_planned_action: true
  LOW:
    threshold: 0.6
    max_per_file: 15
    require_consideration: true
  INFO:
    threshold: 0.5
    max_per_file: 20
    informational_only: true

# Finding validation rules
finding_validation:
  required_fields:
    - id
    - rule_id
    - title
    - description
    - severity
    - confidence
    - file_path
    - evidence

validation_rules:
  # Finding validation
  finding_validation:
    # Structure validation
    structure:
      required_fields:
        - id
        - rule_id
        - title
        - description
        - severity
        - confidence
        - file_path
        - evidence
      
      field_constraints:
        confidence:
          min: 0.0
          max: 1.0
          precision: 2
        severity:
          allowed_values: ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
        title:
          max_length: 100
          min_length: 10
        description:
          max_length: 500
          min_length: 20
    
    # Content validation
    content:
      # Evidence requirements
      evidence_requirements:
        critical_severity_min_evidence: 3
        high_severity_min_evidence: 2
        medium_severity_min_evidence: 1
        low_severity_min_evidence: 1
        
      # Code snippet validation
      code_snippet_validation:
        require_line_numbers: true
        validate_syntax: true
        max_snippet_lines: 20
        min_context_lines: 2
        
      # Reasoning validation
      reasoning_validation:
        require_explanation: true
        min_explanation_length: 50
        require_solution_suggestion: true

  # Recommendation validation
  recommendation_validation:
    # Structure requirements
    structure:
      required_fields:
        - title
        - description
        - priority
        - effort_estimate
        - impact_assessment
        - implementation_guidance
      
      field_constraints:
        priority:
          allowed_values: ["CRITICAL", "HIGH", "MEDIUM", "LOW"]
        effort_estimate:
          allowed_values: ["MINIMAL", "LOW", "MEDIUM", "HIGH", "EXTENSIVE"]
        impact_assessment:
          allowed_values: ["CRITICAL", "HIGH", "MEDIUM", "LOW", "MINIMAL"]
    
    # Content requirements
    content:
      actionability:
        require_specific_steps: true
        include_code_examples: true
        provide_alternatives: true
        
      feasibility:
        consider_technical_constraints: true
        assess_resource_requirements: true
        evaluate_risk_factors: true

  # Agent result validation
  result_validation:
    # Completeness checks
    completeness:
      min_findings_for_analysis: 1
      max_findings_per_file: 25
      require_summary: true
      require_metrics: true
      
    # Consistency checks
    consistency:
      severity_distribution_balance: true
      confidence_score_alignment: true
      finding_recommendation_alignment: true
      
    # Quality thresholds
    quality_thresholds:
      min_average_confidence: 0.6
      max_low_confidence_findings: 5
      min_evidence_coverage: 0.8

severity_calibration:
  # Severity assignment rules
  severity_rules:
    critical:
      conditions:
        - security_vulnerability: true
        - data_loss_risk: true
        - system_failure_risk: true
        - regulatory_violation: true
      confidence_threshold: 0.9
      
    high:
      conditions:
        - performance_degradation: true
        - maintainability_severe: true
        - scalability_blocker: true
        - best_practice_major_violation: true
      confidence_threshold: 0.8
      
    medium:
      conditions:
        - code_smell_significant: true
        - performance_minor: true
        - maintainability_moderate: true
        - best_practice_violation: true
      confidence_threshold: 0.7
      
    low:
      conditions:
        - style_violation: true
        - minor_optimization: true
        - documentation_improvement: true
        - preference_based_suggestion: true
      confidence_threshold: 0.6

  # Severity escalation rules
  escalation_rules:
    # Frequency-based escalation
    frequency_escalation:
      repeated_pattern_threshold: 3
      escalation_severity_levels: 1
      
    # Context-based escalation
    context_escalation:
      critical_system_components: 
        - authentication
        - payment_processing
        - data_encryption
        - api_endpoints
      escalation_multiplier: 1.5
      
    # Impact-based escalation
    impact_escalation:
      high_traffic_components: 1.3
      core_business_logic: 1.4
      shared_utilities: 1.2

confidence_calibration:
  # Confidence scoring rules
  confidence_rules:
    # Evidence-based scoring
    evidence_scoring:
      direct_code_evidence: 0.3
      documentation_reference: 0.2
      best_practice_reference: 0.2
      industry_standard_reference: 0.2
      expert_consensus: 0.1
      
    # Uncertainty factors
    uncertainty_factors:
      incomplete_context: -0.2
      ambiguous_requirements: -0.15
      novel_technology: -0.1
      complex_interaction: -0.1
      
    # Confidence boosters
    confidence_boosters:
      multiple_evidence_sources: 0.1
      cross_agent_validation: 0.15
      historical_pattern_match: 0.1
      automated_tool_confirmation: 0.2

  # Confidence validation
  confidence_validation:
    # Calibration checks
    calibration_checks:
      validate_against_evidence: true
      check_uncertainty_accounting: true
      verify_confidence_intervals: true
      
    # Adjustment rules
    adjustment_rules:
      min_confidence_with_evidence: 0.5
      max_confidence_without_strong_evidence: 0.8
      uncertainty_penalty_factor: 0.9

output_formatting:
  # Standardization rules
  standardization:
    # Message formatting
    message_formatting:
      use_consistent_terminology: true
      follow_style_guide: true
      include_context_information: true
      
    # Code reference formatting
    code_formatting:
      include_file_paths: true
      use_relative_paths: true
      include_line_numbers: true
      format_code_snippets: true
      
    # Metric formatting
    metric_formatting:
      use_standard_units: true
      include_scale_references: true
      provide_context_comparison: true

  # Accessibility requirements
  accessibility:
    # Language clarity
    language_clarity:
      avoid_technical_jargon: true
      provide_definitions: true
      use_plain_language: true
      
    # Information hierarchy
    information_hierarchy:
      prioritize_critical_information: true
      use_progressive_disclosure: true
      provide_executive_summaries: true

quality_metrics:
  # Analysis quality metrics
  analysis_quality:
    # Accuracy metrics
    accuracy:
      precision_target: 0.85
      recall_target: 0.80
      f1_score_target: 0.82
      
    # Completeness metrics
    completeness:
      coverage_target: 0.90
      thoroughness_target: 0.85
      
    # Consistency metrics
    consistency:
      inter_agent_agreement_target: 0.80
      temporal_consistency_target: 0.85

  # Performance metrics
  performance_quality:
    # Efficiency metrics
    efficiency:
      max_analysis_time_minutes: 10
      max_memory_usage_mb: 512
      min_throughput_files_per_minute: 5
      
    # Reliability metrics
    reliability:
      max_error_rate: 0.05
      min_uptime_percentage: 99.0
      max_timeout_rate: 0.02

# Continuous monitoring
monitoring:
  # Quality monitoring
  quality_monitoring:
    # Real-time monitoring
    real_time:
      track_confidence_scores: true
      monitor_finding_quality: true
      detect_quality_degradation: true
      
    # Batch monitoring
    batch_analysis:
      daily_quality_reports: true
      weekly_trend_analysis: true
      monthly_calibration_review: true

  # Alerting rules
  alerting:
    # Quality alerts
    quality_alerts:
      low_confidence_rate_threshold: 0.3
      high_error_rate_threshold: 0.1
      quality_degradation_threshold: 0.2
      
    # Performance alerts
    performance_alerts:
      high_response_time_threshold: 300
      memory_usage_threshold: 80
      timeout_rate_threshold: 0.05
