agent:
  id: "cloud_native"
  name: "Cloud Native Agent"
  description: "Cloud-native architecture and container practices analysis"
  type: "LlmAgent"
  model: ${LLM_MODEL}
  instructions: |
    You are a cloud architecture expert specializing in cloud-native development.
    Review code for container readiness, Kubernetes compatibility, cloud service 
    integration, and adherence to 12-factor app principles.
  tools:
    - "container_analyzer"
    - "k8s_validator"
    - "scalability_checker"
  output_key: "cloud_native_analysis"