# ADK Agent Configuration
# Configuration for ADK BaseAgent implementation and agent lifecycle management

agent:
  # Base agent configuration
  base:
    name: "ADK-BaseAgent"
    description: "Base agent implementation for ADK multi-agent system"
    version: "1.0.0"
    
  # Execution configuration
  execution:
    default_timeout: 300  # 5 minutes
    quick_timeout: 60     # 1 minute  
    long_timeout: 900     # 15 minutes
    max_retries: 3
    retry_backoff_base: 2
    
  # Memory and resource limits
  resources:
    max_memory_mb: 512
    max_execution_time: 600  # 10 minutes
    max_concurrent_operations: 5
    
  # Health check configuration
  health:
    check_interval: 30  # seconds
    timeout: 10         # seconds
    max_failed_checks: 3
    
  # Logging configuration
  logging:
    level: "INFO"
    include_context: true
    include_metrics: true
    correlation_id_header: "X-Correlation-ID"
    
  # Agent lifecycle
  lifecycle:
    startup_timeout: 60   # seconds
    shutdown_timeout: 30  # seconds
    graceful_shutdown: true
    
# Session management
session:
  default_timeout: 7200    # 2 hours
  max_timeout: 86400       # 24 hours
  cleanup_interval: 3600   # 1 hour
  inactivity_timeout: 1800 # 30 minutes
  max_sessions_per_user: 10
  
# Workflow configuration
workflow:
  default_timeout: 1800  # 30 minutes
  max_agents: 20
  max_depth: 5
  execution_strategy: "sequential"  # or "parallel"
  
# Performance monitoring
monitoring:
  collect_metrics: true
  metrics_interval: 60  # seconds
  performance_tracking: true
  resource_monitoring: true
  
# Error handling
error_handling:
  capture_stack_traces: true
  include_context: true
  retry_on_transient_errors: true
  transient_error_codes: ["TIMEOUT", "NETWORK_ERROR", "RATE_LIMIT"]
  
# Security
security:
  validate_inputs: true
  sanitize_outputs: true
  max_input_size: 10485760  # 10MB
  allowed_file_types: [".py", ".js", ".ts", ".java", ".go", ".rb", ".php", ".cpp", ".c", ".cs"]
