# ADK Session Service Configuration
# Configuration for ADK InMemorySessionService and session management

session_service:
  # Service configuration
  service:
    name: "ADK-InMemorySessionService"
    description: "In-memory session service for ADK agents"
    version: "1.0.0"
    
  # Session storage configuration
  storage:
    type: "in_memory"
    max_sessions: 1000
    session_ttl: 7200  # 2 hours
    cleanup_interval: 300  # 5 minutes
    persist_to_disk: false
    
  # Session lifecycle
  lifecycle:
    create_timeout: 10      # seconds
    update_timeout: 5       # seconds
    delete_timeout: 5       # seconds
    batch_operations: true
    
  # Memory management
  memory:
    max_memory_per_session: 50  # MB
    total_memory_limit: 2048    # MB
    gc_threshold: 0.8           # Trigger cleanup at 80% memory
    compression_enabled: true
    
  # Concurrency control
  concurrency:
    max_concurrent_sessions: 100
    session_lock_timeout: 30     # seconds
    read_write_locks: true
    deadlock_detection: true
    
  # Monitoring and metrics
  monitoring:
    track_session_metrics: true
    metrics_retention: 3600      # 1 hour
    performance_logging: true
    session_analytics: true
    
  # Session data
  data:
    max_session_data_size: 10    # MB
    serialization_format: "json"
    compression_algorithm: "gzip"
    encryption_at_rest: false
    
  # Error handling
  error_handling:
    auto_recovery: true
    orphaned_session_cleanup: true
    corruption_detection: true
    backup_on_error: true
    
# Session validation
validation:
  session_id_format: "uuid4"
  required_fields: ["session_id", "created_at", "status"]
  max_session_name_length: 100
  allowed_status_values: ["active", "completed", "failed", "timeout", "cancelled"]
  
# Agent session integration
agent_integration:
  session_per_agent: false
  shared_session_data: true
  agent_isolation: "namespace"  # or "process"
  cross_agent_communication: true
  
# Persistence (for future disk-based implementation)
persistence:
  enabled: false
  storage_path: "./data/sessions"
  backup_interval: 3600  # 1 hour
  backup_retention: 168  # 1 week in hours
  
# Security
security:
  session_encryption: false
  access_control: true
  audit_logging: true
  session_hijacking_protection: true
